name: acme-cloudflare-callback
version: "1.0"
services:
  - name: acme-callback
    mode: replicated
    replicas: 1
    variables:
      - name: CF_API_TOKEN
        value-from-vault-secret:
          vault: acme-secrets
          secret: cloudflare-credentials
          key: api-token
    containers:
      - name: acme-callback
        image: avassa/acme-cloudflare-callback:1.0
        approle: acme-callback
        env:
          CF_API_TOKEN: ${CF_API_TOKEN}
          VOLGA_ROLE_ID: "acme-role-id"
          APPROLE_SECRET_ID: ${SYS_APPROLE_SECRET_ID}
          API_CA_CERT: ${SYS_API_CA_CERT}
          CF_API_BASE: "https://api.cloudflare.com/client/v4"
          CF_DEFAULT_TTL: "120"
          AVASSA_API_HOST: "https://api.internal:4646"
          MANAGED_DOMAINS: ${MANAGED_DOMAINS}
          ACME_DEBUG_DNS_VERIFICATION: "true"
        restart-policy: always
